# Generated by Django 4.0.2 on 2022-02-12 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('comments_num', models.IntegerField()),
                ('stars_num', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('source', models.URLField()),
                ('using_duration', models.CharField(choices=[(1, 'менее месяца'), (2, 'не более года'), (3, 'более года')], max_length=255)),
                ('advantages', models.TextField(max_length=3000)),
                ('disadvantages', models.TextField(max_length=3000)),
                ('content', models.TextField(max_length=3000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='opinions.product')),
            ],
        ),
    ]
